# locals hosting for postgres
services:
  postgres:
    image: postgis/postgis:latest
    container_name: windydb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cyclist
      POSTGRES_PASSWORD: bikes
      POSTGRES_DB: windy-db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: