[project]
name = "tailwind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.1.7",
    "dotenv>=0.9.9",
    "psycopg[binary]>=3.2.5",
]
