# Generated by Django 5.1.7 on 2025-03-11 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("strava_id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("user_name", models.CharField(max_length=255, null=True)),
                ("gender", models.CharField(max_length=25, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("access_token", models.CharField(max_length=255)),
                ("refresh_token", models.CharField(max_length=255)),
                ("expires_at", models.IntegerField()),
            ],
        ),
    ]
